version: 0.0
os: linux
files:
  - source: /target
    destination: /home/ec2-user/my-web-server
permissions:
  - object: /home/ec2-user/my-web-server
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: root